### ISSUE TITLE
No players shutdown timeout

### ISSUE THREAD

**Issue by MaxBQb** [Druzai/Bot_Mc_discord#29]
Bot option to stop server when no players found during long period of time.
Timeout < 0 = disabled

**Comment by MaxBQb** [comment]
`%status` stop info:

![image](https://user-images.githubusercontent.com/27343275/150322710-ac6e36fa-9054-4070-b692-96216bfdb1d2.png)
Message ENG: 
```Server was stopped automatically at 13:23:54 20.01.2022```
Message RUS:
```Сервер был остановлен автоматически в 13:23:54 20.01.2022```

**Comment by Druzai** [comment]
Cool, but how to set it up for Minecrafters?

Another command or subcommand?

**Comment by MaxBQb** [comment]
Yup

**Comment by Druzai** [comment]
Done in last commit
